language: cpp

os:
  - linux
  - osx

compiler:
    - gcc
    - clang

addons:
  apt:
    packages:
    - libopencv-dev

matrix:
    exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update                                                                               ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install opencv                                                                       ;fi

script:
  - mkdir build && cd build && cmake ..
  - cmake --build . --target install
