language: cpp

#force old image, in the newer ones pip is not available but numpy is still incompatible (and also impossible to remove without pip)
osx_image: xcode7.3

os:
  - linux
  - osx

compiler:
    - gcc
    - clang

addons:
  apt:
    packages:
    - libopencv-dev

matrix:
    exclude:
    - os: osx
      compiler: gcc
    - os: linux
      compiler: clang

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew update                                                                               ;fi
  #remove numpy from xcode7.3 image since it's broken if used by opencv
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then /usr/bin/yes | pip uninstall numpy                                                        ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install opencv                                                                       ;fi
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then brew install opencv@2                                                                     ;fi

script:
  - mkdir build && cd build && cmake ..
  - cmake --build . --target install
