image: Visual Studio 2017
clone_folder: c:\projects\peoplebox
cache: C:\Tools\vcpkg\installed\

environment:
    WORKSPACE: C:\projects
    matrix:
    - platform: Win64
      COMPILER: vs
      configuration: Release
      VCPKG_ROOT: C:\Tools\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows
      USE_CUDA: yes
    - platform: Win64
      COMPILER: vs
      configuration: Debug
      VCPKG_ROOT: C:\Tools\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows
      USE_CUDA: yes
    - platform: Win64
      COMPILER: vs
      configuration: Release
      VCPKG_ROOT: C:\Tools\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows
      USE_CUDA: no
    - platform: Win64
      COMPILER: vs
      configuration: Debug
      VCPKG_ROOT: C:\Tools\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows
      USE_CUDA: no

install:
  - cinst cmake ninja
  - SET "PATH=C:\Program Files\CMake\bin;%PATH%"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - git submodule -q update --init --recursive
  - cd %WORKSPACE%\
  - if [%USE_CUDA%]==[yes] curl -L https://developer.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.105_418.96_win10.exe -o setup.exe
  - if [%USE_CUDA%]==[yes] .\setup.exe -s nvcc_10.1 cuobjdump_10.1 nvprune_10.1 cupti_10.1 gpu_library_advisor_10.1 memcheck_10.1 nvdisasm_10.1 nvprof_10.1 visual_profiler_10.1 visual_studio_integration_10.1 cublas_10.1 cublas_dev_10.1 cudart_10.1 cufft_10.1 cufft_dev_10.1 curand_10.1 curand_dev_10.1 cusolver_10.1 cusolver_dev_10.1 cusparse_10.1 cusparse_dev_10.1 nvgraph_10.1 nvgraph_dev_10.1 npp_10.1 npp_dev_10.1 nvrtc_10.1 nvrtc_dev_10.1 nvml_dev_10.1 occupancy_calculator_10.1 fortran_examples_10.1
  - if [%USE_CUDA%]==[yes] set CUDA_PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v10.1
  - if [%USE_CUDA%]==[yes] set CUDA_PATH_V10_1=%CUDA_PATH%
  - if [%USE_CUDA%]==[yes] set CUDA_TOOLKIT_ROOT_DIR=%CUDA_PATH%
  - if [%USE_CUDA%]==[yes] set PATH=%CUDA_PATH%\bin;%PATH%
  - cd %VCPKG_ROOT%
  - git pull
  - .\bootstrap-vcpkg.bat
  - if [%USE_CUDA%]==[yes] vcpkg install cuda
  - vcpkg install opencv[ffmpeg]  ## opencv[ffmpeg,cuda] is too big to build, timing out (>1h).
  - vcpkg install jsoncons stb
  - vcpkg install darknet[opencv]
  - cd %WORKSPACE%\peoplebox\
  - mkdir build_debug && cd build_debug
  - if [%configuration%]==[Debug] cmake -G "Visual Studio 15 2017" -T "host=x64" -A "x64" "-DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake" "-DVCPKG_TARGET_TRIPLET=%VCPKG_DEFAULT_TRIPLET%" -DCMAKE_BUILD_TYPE="Debug" ..
  - cd ..
  - mkdir build_release && cd build_release
  - if [%configuration%]==[Release] cmake -G "Visual Studio 15 2017" -T "host=x64" -A "x64" "-DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake" "-DVCPKG_TARGET_TRIPLET=%VCPKG_DEFAULT_TRIPLET%" -DCMAKE_BUILD_TYPE="Release" ..
  - cd ..

build_script:
  - if [%configuration%]==[Debug]   cd build_debug   && cmake --build . --config Debug --parallel 8 --target install   && cd ..
  - if [%configuration%]==[Release] cd build_release && cmake --build . --config Release --parallel 8 --target install && cd ..

artifacts:
  - path: '*.exe'
